### ISSUE TITLE
笔记格式解析不正确

### ISSUE THREAD

**Issue by byheaven** [devinmugen/kindle2Readwise#1]
hi，非常感谢您分享这个小工具，解决了使用kindle和readwise的最大痛点！
在使用中发现如下这种某些包含笔记的情况(例如readwise本身支持通过添加.c1, .c2这样的笔记来自动合并标注)，解析后的csv结果不正确，具体表现是会污染location列，但是不知道可否改进一下？谢谢！

```
王信文公众号合集 (王信文)
- 您在第 21 页（位置 #313-314）的标注 | 添加于 2022年5月15日星期日 上午1:35:23

这件事给我两个影响：第⼀，我试着不那么“喜形于⾊”了。因为我的情绪⼀旦被观察到，就会降低 公司的决策效率，甚⾄影响决策的正确性。
==========
﻿王信文公众号合集 (王信文)
- 您在第 21 页（位置 #314）的笔记 | 添加于 2022年5月15日星期日 上午1:35:36

.c1
==========
﻿王信文公众号合集 (王信文)
- 您在第 21 页（位置 #318-321）的标注 | 添加于 2022年5月15日星期日 上午1:36:19

第⼆，我试着尽量把所有业务决策过程“算法”化。以市场预算为例，经过讨论，我把市场预算定为 每个⽉预期收⼊的固定百分⽐。随着收⼊变化，市场预算⾃然变化，不再需要我⼈为⼲预。换⾔ 之，我需要花⼤量时间研究正确的算法应该是怎样的。算法研究出来之后，不需要轻易变动，不 再需要拍我的脑袋，决策的准确性也得⼤幅提升。
==========
﻿王信文公众号合集 (王信文)
- 您在第 21 页（位置 #321）的笔记 | 添加于 2022年5月15日星期日 上午1:36:27

.c2
==========
```
解析结果csv：<img width="924" alt="image" src="https://user-images.githubusercontent.com/30173023/168516164-451e383f-d3ed-4251-b824-86bee6128f37.png">

**Comment by devinryu** [comment]
已解决

![image](https://user-images.githubusercontent.com/42215787/169950558-1910c8b3-e2a1-42b4-962f-581cead8b4c4.png)
